version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-5+gulo&-k+^k55t18^u7jot6$_dncz3d=$%whgpjzjizfji=g$
      - DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./image_files:/app/image_files
      - ./audio_files:/app/audio_files
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s