
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
    volumes:
      - ./uploads:/app/uploads
      - ./image_files:/app/image_files
      - ./audio_files:/app/audio_files
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s