# Generated by Django 4.2.13 on 2025-07-30 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('conversion_type', models.CharField(choices=[('audio_to_image', 'Audio to Image'), ('image_to_audio', 'Image to Audio')], max_length=20)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('description_prompt', models.TextField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_data', models.BinaryField()),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='app.conversionsession')),
            ],
        ),
    ]
